import "./globals.css";
import Links from './components/links'
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Links></Links>
        {/* Layout UI */}
        <main>{children}</main>
      </body>
    </html>
  )
}
